version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 8080 di host ke port 80 di container
    volumes:
      - .:/usr/share/nginx/html
